### ISSUE TITLE
Integration Tests failure

### ISSUE THREAD

**Issue by MarcoFierimonte** [jayeshgarg/OSGiPractice#2]
Hello Jayesh,

I have tried your project, I am interesting to learn how to do Integration Tests in OSGi environment. After I download the project and compile it I got the following error on Integration Tests: 

[com.gargjayesh.practice.karaf.integrationtest.testcases.ITTemperatureRestTest.txt](https://github.com/jayeshgarg/OSGiPractice/files/934228/com.gargjayesh.practice.karaf.integrationtest.testcases.ITTemperatureRestTest.txt)

Have you any idea about it? 
Thank you.

Marco

**Comment by jayeshgarg** [comment]
I hope your query will be resolved now.

Apologies for the delayed response.

Please note, I am unable to make it work with `versionAsInProject()` hence I changed it to specific version.
